feat: shipping method
Orckestra/orc-vsf pull request #47
Opened 2022-07-08 15:17 UTC by oleksandr-honcharuk

shipping method

## Description

implement select shipping method in checkout 

## Related Issue

AB#61984
AB#60291

## Motivation and Context

second step of checkout, selecting shipping method

## How Has This Been Tested?

select shipping fulfilment method
fill address
click select shipping method

## Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/55245278/178020517-10198b42-8980-4914-9cbc-9604664dce8b.png)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-07-11 08:13 UTC, InnaBoitsun requested changes

2022-07-11 08:13 UTC, InnaBoitsun commented on packages/composables/src/getters/cartGetters.ts
> +}
we already have getActiveShipment(cart)

2022-07-11 08:13 UTC, InnaBoitsun commented on packages/theme/components/Checkout/AddressForm.vue
> +  name: 'AddressForm',
Is this possible to re-use existent ShippingAddressForm.vue ( just rename it to UserAddressForm.vue) ?

2022-07-11 08:13 UTC, InnaBoitsun commented on packages/theme/pages/Checkout/Shipping.vue
> +    };
looks like you do not update shipping method in cart when it is selected . need to update it

2022-07-11 08:52 UTC, InnaBoitsun commented on packages/theme/pages/Checkout/Shipping.vue
> +                    <div v-if="isOpen[item.id]" class="shipping__info">
use existent AddressPreview component for detailed info

2022-07-11 09:29 UTC, InnaBoitsun commented on packages/theme/pages/Checkout/Shipping.vue
>            </SfButton>
this button should Go to Payment and activated when Shipping is ready

2022-07-11 17:27 UTC, oleksandr-honcharuk commented on packages/theme/components/Checkout/AddressForm.vue
> +  name: 'AddressForm',
ShippingAddressForm has actions inside 
we can implement AddressForm to ShippingAddressForm in feature

2022-07-12 07:45 UTC, InnaBoitsun requested changes

2022-07-12 07:45 UTC, InnaBoitsun commented on packages/theme/pages/Checkout/Shipping.vue
> +      loadCountries(),
loadCountries already present in default layout, you can remove it here

2022-07-12 07:45 UTC, InnaBoitsun commented on packages/theme/pages/Checkout/Shipping.vue
> +    const shipment = cartGetters.getActiveShipment(cart.value);
use computed(() =>

2022-07-12 13:21 UTC, InnaBoitsun commented on packages/theme/pages/Checkout/Shipping.vue
> +              class="action-button sf-button form__action-button--add-address"
please use class sf-button--text to be as lint

2022-07-12 14:49 UTC, merged