feat: implement orders history, order details
Orckestra/orc-vsf pull request #50
Opened 2022-07-13 12:22 UTC by OlyaAn

Implement orders history,  order details

## Related Issue
AB#60287
AB#60288

## Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/59433752/178732331-78d78910-434b-484e-924a-0feb1aa13dd4.png)
![image](https://user-images.githubusercontent.com/59433752/178732396-9f497066-9cd9-43fd-8b60-e9b0a68a73b9.png)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-07-13 15:21 UTC, InnaBoitsun requested changes

2022-07-13 15:21 UTC, InnaBoitsun commented on packages/theme/pages/MyAccount/OrderHistory.vue
> +    };
update to have like this:

 ```
const getStatusTextClass = (order) => {
      const status = ordersHistoryGetters.getStatus(order);
      switch (status) {
        case 'InProgress':
          return 'text-warning';
        case 'Completed':
          return 'text-success';
        case 'Canceled':
          return 'text-danger';
        default:
          return 'text-info';
      }
    };
```

2022-07-13 15:21 UTC, InnaBoitsun commented on packages/theme/pages/MyAccount/OrderHistory.vue
> +    ];
tables should be the same, please create separate component OrdersList.vue and use it something like this
 <SfTab title="My current orders">
<OrdersList :orders="currentOrders"  .../>
</SfTab>
 <SfTab title="My past orders">
  <OrdersList :orders="pastOrders" .../>

For tablle use next columns lables:
      "Order Number",
      "Date",
      "Total",
      "Status",

2022-07-13 15:21 UTC, InnaBoitsun commented on packages/theme/pages/MyAccount/OrderHistory.vue
> +          <p>Total orders Past - {{ totalOrdersPast }}</p>
plase display totals in Tabs label
My current orders (X)
My past orders (X)

2022-07-13 15:21 UTC, InnaBoitsun commented on packages/theme/pages/MyAccount/OrderHistory.vue
> +      </div>
the Shipping cost is absent in order summary

2022-07-15 11:00 UTC, OlyaAn commented on packages/api-client/src/api/orders/getOrders/index.ts
> +  const filters =
fixed as filterMember, filterValues

2022-07-15 11:09 UTC, OlyaAn commented on packages/api-client/src/types.ts
> +    billingCurrency: string,
![image](https://user-images.githubusercontent.com/59433752/179211734-18631c97-f62e-4efb-8971-3b18efc61282.png)
![image](https://user-images.githubusercontent.com/59433752/179211802-eeb961d5-51b1-4118-9624-b168e185d0a7.png)
UserOrder we use for order details and OrderItem we use for orders in the history object. Here totally different models
@InnaBoitsun

2022-07-15 11:19 UTC, InnaBoitsun commented on packages/api-client/src/api/orders/findOrders/index.ts
> +  console.log(JSON.stringify(body));
remove console.log

2022-07-15 11:19 UTC, InnaBoitsun commented on packages/api-client/src/api/orders/findOrders/index.ts
> +  console.log(JSON.stringify(data));
remove console.log

2022-07-15 11:36 UTC, InnaBoitsun commented on packages/composables/src/getters/orderGetters.ts
> +}
this getter is wrong, calculation is wrong
it should include Item +  Saving + Coupons + rewards 

for now you can remove using it in Order Details, we will need to fix it later as bug

2022-07-15 12:18 UTC, InnaBoitsun approved these changes

2022-07-15 12:59 UTC, merged