Open Close store
Orckestra/orc-vsf pull request #66
Opened 2022-08-03 12:53 UTC by neexite

#AD61987

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-08-03 13:34 UTC, Anstsiya commented on packages/theme/components/Store/StoreSchedule.vue
> +    const openingHours = schedule?.openingHours?.find(o => o.day === dayOfWeek);
first you have to check if the today's date contains in schedule.openingHourExceptions. There can be specific schedule for this date, or the date can be inside of the period with the specific schedule. Pay attention that exception can be recurrent.

2022-08-03 13:34 UTC, Anstsiya commented on packages/theme/components/Store/StoreSchedule.vue
> +      const beginingTime = today.add(dayjs.duration(time.beginingTime));
There can be the case if you have hours 00:00 it will save it like PT0S for beginning and P1D for ending. This case can be unparseable for dayjs

2022-08-03 13:34 UTC, Anstsiya commented on packages/theme/components/StoresList.vue
> +            <strong>{{ label }}</strong>123
guess it should be removed

2022-08-03 13:45 UTC, Anstsiya commented on packages/theme/components/StoresList.vue
> +          <StoreSchedule :schedule="item.storeSchedule" :timezoneName="item.fulfillmentLocation.timeZone" />
You take a store schedule. Are you sure we have to take this one, or maybe pickup schedule as it is a pickup method ?

2022-08-05 11:43 UTC, InnaBoitsun requested changes

2022-08-05 11:43 UTC, InnaBoitsun commented on packages/theme/components/Store/StoreSchedule.vue
> +      <span v-for="item in openingTimes" :key="item"> {{ item.beginingTime.format('HH:mm') }}-{{ item.endingTime.format('HH:mm') }} </span>
because of :key="item" there are errors in console
**Avoid using non-primitive value as key, use string/number value instead.**
try to use next:
`<span v-for="(item, index) in openingTimes" :key="index">`

2022-08-05 11:43 UTC, InnaBoitsun commented on packages/api-client/src/api/stores/findStores/index.ts
> +  const { api, scope } = context.config;
getCachedShedules => getCachedSchedules

2022-08-05 11:43 UTC, InnaBoitsun commented on packages/api-client/src/api/stores/findStores/index.ts
> +  const value = context.cache?.get(cacheKey);
Shedules -> **Sch**edules

2022-08-05 11:43 UTC, InnaBoitsun commented on packages/api-client/src/api/stores/findStores/index.ts
> +
if 300  is seconds and = 5 minutes, I think we can add more time for the cache as on the website.
On website we have  **3 hours** <category name="StoreSchedule" profileName="LongLived" />

2022-08-05 11:43 UTC, InnaBoitsun commented on packages/theme/components/Store/StoreSchedule.vue
> +  name: 'StoreSchedule',
as this component display just status and hours for **TODAY**, please rename the component to
**TodayScheduleStatus** and display information in next format:

2022-08-05 11:43 UTC, InnaBoitsun commented on packages/theme/components/Store/StoreSchedule.vue
> +      <span v-if="isOpen" class="open">{{ $t('Open') }}</span>
use next classes: "color-primary sf-badge" for OPEN and  "color-danger sf-badge" for Closed

2022-08-05 11:50 UTC, InnaBoitsun commented on packages/api-client/src/api/stores/findStores/index.ts
> +      storeSchedule: getSchedule(result.id, 'OpeningHours')
because of this change we need to update docs in docs\guide\use-stores.md , extend the description for type Store and add these properties and define a new type **FulfillmentSchedule** ...

2022-08-05 12:22 UTC, InnaBoitsun approved these changes

2022-08-05 12:41 UTC, Anstsiya approved these changes

2022-08-05 12:42 UTC, merged